### ISSUE TITLE
Add @open-telemetry/collector-contrib-approvers with write access

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go-build-tools#137]
Please +1 that we are ok to add @open-telemetry/collector-contrib-approvers with write access since the group is owner of `chloggen`.

cc @open-telemetry/go-maintainers @open-telemetry/collector-maintainers

**Comment by Aneurysm9** [comment]
:+1: 

I would be good with adding @open-telemetry/go-approvers, @open-telemetry/collector-approvers, and @open-telemetry/collector-contrib-approvers with the same permissions they have on their respective repos.
