### ISSUE TITLE
Update crosslink to support go workspaces

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-go-build-tools#140]
Related issues/PRs:
https://github.com/open-telemetry/opentelemetry-collector/pull/5993
https://github.com/open-telemetry/opentelemetry-collector/issues/5991

Collector core is looking to move to use go workspaces instead of having replace statements in respective `go.mod` files. Crosslink can be updated to add a `crosslink workspaces` command that will create a single go workspace file at the root directory. 

Would there be any additional requirements required for this?

**Comment by codeboten** [comment]
Is crosslink still needed? I was under the impression that go workspace makes replace statements for module dependencies within the same monorepo obsolete.

**Comment by bryan-aguilar** [comment]
I agree, the hole I could see crosslink filling is the automation of creating workspace files. Is that a mechanism that could be useful?

**Comment by jpkrohling** [comment]
We won't need to create workspace files periodically. Whenever there's a new module, it will need to be included there, but that's it.

**Comment by bryan-aguilar** [comment]
It seems like this upgrade won't even be necessary then as long as workspaces can be used as is.
