### ISSUE TITLE
[cmd/chloggen] Parse command line args with github.com/spf13/cobra

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-go-build-tools#141]
We use `github.com/spf13/cobra` in this project already. It should simplify all the command args parsing. WDYT?

_Originally posted by @dmitryax in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11540#discussion_r909198391_

**Comment by codeboten** [comment]
I started working on this without realizing it was already assigned. Apologies @TomasLongo, please take a look at the PR
