### ISSUE TITLE
Can `multimod tag` also push the tags to the upstream repository?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go-build-tools#157]

**Comment by bryan-aguilar** [comment]
Thoughts on adding a `--push` flag to `multimod tag`? `multimod tag --push` will push to the repository and will be opt in. By default it will push to the remote named `upstream` but can be overridden with an environment variable named `MM_REMOTE`.

**Comment by bogdandrutu** [comment]
I like that.

**Comment by bryan-aguilar** [comment]
Yup, that that makes more sense to me also.
