### ISSUE TITLE
Document release process for this repo

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-go-build-tools#185]
Currently the module is at 0.2.0 but the repo only shows 0.1.0 under releases https://github.com/open-telemetry/opentelemetry-go-build-tools/releases.

We need to document the release process for this repo to ensure it is done consistently across releases.

**Comment by bogdandrutu** [comment]
Done https://github.com/open-telemetry/opentelemetry-go-build-tools/releases/tag/v0.2.0 :))

**Comment by pellared** [comment]
I have done it as part of https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/325
