### ISSUE TITLE
Request to drop the usage of replace in multimod, crosslink and semconvgen

### ISSUE THREAD

**Issue by sanathkumarbs** [open-telemetry/opentelemetry-go-build-tools#236]
**Issue:**

The`opentelemetry-collector` depends on `multimod`, `crosslink`, and `semconvgen`  as `install-tools` for performing `make`. It's currently not possible to install `multimod`, `crosslink`, and `semconvgen`  due to `go install`'s limitation of not allowing modules that contain `replace` directives in the `go.mod` file. 

A thread related to this can be found here: https://github.com/golang/go/issues/44840

It currently looks like `multimod`, `crosslink`, and `semconvgen` are using `replace` directives in their `go.mod` files.

**Additional Information**
* I couldn't find an executable built for the above packages that can be installed. So, I'm opening an issue here. 
* It also seems to be that `multimod`, `crosslink`, and `semconvgen` are all non-main packages, I wonder if there's even a way to install it without building it myself locally

**Current Behavior**
```
cd ./internal/tools && go install go.opentelemetry.io/build-tools/crosslink@latest
go: downloading go.opentelemetry.io/build-tools/crosslink v0.5.0
go: go.opentelemetry.io/build-tools/crosslink@latest (in go.opentelemetry.io/build-tools/crosslink@v0.5.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

cd ./internal/tools && go install go.opentelemetry.io/build-tools/multimod@latest
go: downloading go.opentelemetry.io/build-tools/multimod v0.5.0
go: go.opentelemetry.io/build-tools/multimod@latest (in go.opentelemetry.io/build-tools/multimod@v0.5.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

go: go.opentelemetry.io/build-tools/semconvgen@latest (in go.opentelemetry.io/build-tools/semconvgen@v0.5.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Expected Behavior**
The installation should happen without errors

**Comment by Aneurysm9** [comment]
These tools are designed for use by the OpenTelemetry Collector and Go SDK repositories.  Each of those repositories include an `internal/tools` module that specifies the versions of all tools it requires and all tool builds are done in the context of that module and built tools are put in a `.tools` directory for use.  These tools are not installed globally with `go install`.  See, e.g., how `multimod` is [built before use](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/4018578884/jobs/6904371149#step:13:7) in a test workflow.  As these are all development tools intended to be used in this manner, where multiple repositories may require the tools at various versions, and require the use of `replace` directives to be effectively tested in this repository between tagged releases, I don't think that change is necessary or desired here.

**Comment by sanathkumarbs** [comment]
Thanks, @Aneurysm9, for your feedback. Interestingly, the onboarding experience on OpenTelemetry Collector requires performing a `make install-tools` to setup all deps, and, the above failures are from running the `make install-tools`. 

I wonder if we need to fix the `make install-tools` to work similarly to the test workflow you linked above.

**Comment by Aneurysm9** [comment]
This is how `make install-tools` works in the Collector repo:

```console
$ rm -r .tools 
$ make install-tools
mkdir -p /Users/mirabant/dev/opentelemetry-collector/.tools
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/misspell -trimpath github.com/client9/misspell/cmd/misspell
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/golangci-lint -trimpath github.com/golangci/golangci-lint/cmd/golangci-lint
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/addlicense -trimpath github.com/google/addlicense
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/porto -trimpath github.com/jcchavezs/porto/cmd/porto
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/go-acc -trimpath github.com/ory/go-acc
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/impi -trimpath github.com/pavius/impi/cmd/impi
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/gocovmerge -trimpath github.com/wadey/gocovmerge
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/checkdoc -trimpath go.opentelemetry.io/build-tools/checkdoc
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/chloggen -trimpath go.opentelemetry.io/build-tools/chloggen
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/crosslink -trimpath go.opentelemetry.io/build-tools/crosslink
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/multimod -trimpath go.opentelemetry.io/build-tools/multimod
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/semconvgen -trimpath go.opentelemetry.io/build-tools/semconvgen
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/apidiff -trimpath golang.org/x/exp/cmd/apidiff
cd /Users/mirabant/dev/opentelemetry-collector/internal/tools && go build -o /Users/mirabant/dev/opentelemetry-collector/.tools/goimports -trimpath golang.org/x/tools/cmd/goimports
```

It is a [make target](https://github.com/open-telemetry/opentelemetry-collector/blob/main/Makefile.Common#L18) that depends on all the individual tool make targets.  This target was [changed recently](https://github.com/open-telemetry/opentelemetry-collector/pull/6974) to improve the isolation of the tooling in that repo, but we've never experienced the reported issue nor had reports of it being an issue.  Can you confirm whether you are able to use `make install-tools` from the `HEAD` of the collector repo or with the `v0.70.0` tag?

**Comment by sanathkumarbs** [comment]
Ah, I don't have this particular change. I'm a commit behind by the looks of it, and still have the older `go install` present in my `Makefile`. 

I'll grab the latest change and I should be good. Thank you for helping me out, @Aneurysm9.
