### ISSUE TITLE
dbotconf: on Windows it produces backslashes instead of slashes

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-build-tools#264]
Using `dbotconf` on Windows results in having backslashes in `directory` field instead of slashes

E.g. 

```
  - package-ecosystem: docker
    directory: \example\zipkin
```

instead of

```
  - package-ecosystem: docker
    directory: /example/zipkin
```

I guess the code misses [`filepath.ToSlash()`](https://pkg.go.dev/path/filepath#ToSlash) in some place(s).

**Comment by venugopal83k** [comment]
@pellared  I would like to work on this issue
