### ISSUE TITLE
`dbconf verify` is not working

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-build-tools#321]
It looks like there is a bug in `dbconf verify`. The `ci` GitHub workflow should fail here: https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/6fd2bd763e919eb562f800dd9df3d63d6a5dd035/.github/workflows/ci.yml#L41
as `make dependabot-check` should fail.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/320#pullrequestreview-1438613489_

**Comment by pellared** [comment]
@CharlieTLe do you want to look at it?

**Comment by CharlieTLe** [comment]
Yes, I can't assign this to myself yet, but I'll take a look.

**Comment by alolita** [comment]
@pellared @Aneurysm9 can you assign this to @CharlieTLe :-)
