### ISSUE TITLE
Add checkfile tool to replace checkdoc

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-go-build-tools#347]
Now that `metadata.yaml` is a requirement on contrib ([PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23340)), we are going to add a check to validate the presence of the file for each component. Once it is also a requirement on core, we would also add the check on core.

Checking for the presence of the `metadata.yaml` for each component is very similar to what `checkdoc` does for `README.md`, the only difference being the file that is checked.

This is a proposal to deprecate `checkdoc` and add `checkfile` instead, where the file to check will be passed as an argument. 
e.g.
```
//	checkfile --project-path path/to/project \
//				--component-rel-path service/defaultcomponents/defaults.go \
//				--module-name go.opentelemetry.io/collector
//				--file-name README.md
```

Like this, we can use `checkfile` for both `README.md` and `metadata.yaml`

**Comment by pellared** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/348
