### ISSUE TITLE
Replace usage of checkdoc by checkfile

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-go-build-tools#349]
Once #348 is merged and released, replace usage of `checkdoc` by `checkfile` in:

- [x] [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) ([PR](https://github.com/open-telemetry/opentelemetry-collector/pull/8144))
- [x] [opentelemetry-lambda](https://github.com/open-telemetry/opentelemetry-lambda) ([PR](https://github.com/open-telemetry/opentelemetry-lambda/pull/828))
- [x] [experimental-arrow-collector](https://github.com/open-telemetry/experimental-arrow-collector) ([PR](https://github.com/open-telemetry/experimental-arrow-collector/pull/58))
- [x] [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) ([PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24643))

**Comment by pellared** [comment]
@mackjmr Do you want to work on this one?

**Comment by mackjmr** [comment]
@pellared, yes I would like to work on this one.
