### ISSUE TITLE
Remove checkdoc

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-build-tools#378]
Follow up after https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/348 and https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/377

**Comment by pellared** [comment]
@mackjmr Do you want to take this?

**Comment by mackjmr** [comment]
@pellared yes, I would like to take this.

**Comment by pellared** [comment]
Done in https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/380
