### ISSUE TITLE
Run go test on Windows

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-build-tools#450]
We should also run `go test` on Windows in CI.

We could try running `test-race` job on both Ubuntu and Windows GitHub runners.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/448#pullrequestreview-1764738324_

**Comment by scorpionknifes** [comment]
Just some notes:

There are 2 tests failing in Windows
- chloggen/cmd/validate_test.go#TestValidateErr
- chloggen/cmd/new_test.go#TestNewErr

```
Error:          "Error: open C:\\...\\opentelemetry-go-build-tools\\chloggen\\cmd\\.chloggen\\TEMPLATE.yaml: The system cannot find the path specified.\n" does not contain "no such file or directory"
```
