### ISSUE TITLE
Release v0.13.0

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-go-build-tools#481]
It's been a while since a release has been done. There is no release cadence for this repository. May be good to get a new one out. 

cc:
@open-telemetry/collector-maintainers 
@open-telemetry/collector-contrib-maintainer 
@open-telemetry/go-maintainers

**Comment by codeboten** [comment]
This was done in March https://github.com/open-telemetry/opentelemetry-go-build-tools/releases/tag/v0.13.0, closing
