### ISSUE TITLE
chloggen prints all output to stdout by default

### ISSUE THREAD

**Issue by mowies** [open-telemetry/opentelemetry-go-build-tools#611]
While doing some debugging, I noticed that chloggen outputs to stdout by default.
That has a few issues in the repos that use this tool, e.g. the opentelemetry-collector repos where the output is redirected to file which doesn't work as it should.

Example:
```
chloggen update --config ./path/to/config --dry 1>stdout.md 2>stderr.md
```

This will result in `stdout.md` being empty and `stderr.md` having the changelog dry run content.

**Comment by mowies** [comment]
I will provide a small fix for this

**Comment by mowies** [comment]
@mx-psi is this worth a release? I feel it affects many things and should probably be updated rather sooner than later

**Comment by mx-psi** [comment]
@mx-psi I would support doing a release for this. Could you create the prep PR following these steps: https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/RELEASING.md ? I can approve and deal with the tagging once it is merged

**Comment by mowies** [comment]
sure, i'll do the prep work :)
should this be 0.14.1 since it's just a bugfix or rather 0.15.0?

**Comment by mowies** [comment]
i'll assume it's 0.15.0 since there basically never was a patch version bump in recent releases :)

**Comment by mx-psi** [comment]
0.15.0 works for me
